
import amc.StudentConnection;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditIA.java
 *
 * Created on Sep 11, 2014, 12:33:17 PM
 */

/**
 *
 * @author Hare Ram
 */
public class EditIA extends javax.swing.JFrame {

    /** Creates new form EditIA */
    String subcode1;
    public EditIA() {
        initComponents();
    }
     public EditIA(String subcod) {
        subcode1=subcod;
         initComponents();
         subcode.setText(subcode1);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        iatable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        usn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        iia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        iiia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        iiiia = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        subcode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("AMC ENGINEERING COLLEGE,BENGALURU");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amc.jpg"))); // NOI18N

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 11));
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Enter the IA marks");

        iatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USN", "IIA", "IIIA", "IIIIA", "Subcode"
            }
        ));
        iatable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iatableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(iatable);

        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("USN");

        jLabel4.setText("I IA");

        jLabel5.setText("II IA");

        jLabel6.setText("III IA");

        jButton5.setText("DELETE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("EXIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("RETRIEVE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel8.setText("Subcode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(usn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(iia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                            .addComponent(iiia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel6)))
                                    .addGap(5, 5, 5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton3)
                                        .addComponent(iiiia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(subcode, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton6)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(631, 631, 631))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(iia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(iiia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(iiiia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(subcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton6)
                    .addComponent(jButton1)
                    .addComponent(jButton7))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(401, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new FacultyLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < iatable.getRowCount(); i++){
            for(int j = 0; j < iatable.getColumnCount(); j++) {
          iatable.setValueAt("", i, j);}
            }
        usn.setText("");
        iia.setText("");
        iiia.setText("");
        iiiia.setText("");
             DefaultTableModel dtm = (DefaultTableModel) iatable.getModel();
             dtm.setRowCount(0);

     //iatable.setModel(new DefaultTableModel());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int index=iatable.getSelectedRow();
        String usn1=iatable.getValueAt(index, 0).toString();
       String usn2=usn.getText();
         String subcode2=subcode.getText();
         if(subcode2.equals(subcode1))
         {
        if(new StudentConnection().update(usn1,usn2,iia.getText(),iiia.getText(),iiiia.getText(),subcode2))
        {
           JOptionPane.showMessageDialog(null, "Successfully Updated");
            usn.setText("");
            iia.setText("");
            iiia.setText("");
            iiiia.setText("");
            //subcode.setText("");
        }
        else
        {
          JOptionPane.showMessageDialog(null,"Not updated");
        }
        }
 else
         {
             JOptionPane.showMessageDialog(null, "You don't have authority to update this subject code");
             usn.setText("");
            iia.setText("");
            iiia.setText("");
            iiiia.setText("");
            subcode.setText(subcode1);
            
 }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String[] options={"yes","No"};
        int answ=JOptionPane.showOptionDialog(null,"Sure to delete??","Delete conform",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[1]);
        if(answ==0)
        {
            int index=iatable.getSelectedRow();
            String usn1=iatable.getValueAt(index, 0).toString();
            String subcod=subcode.getText();
            if(new StudentConnection().delete(usn1,subcod))
        {
            JOptionPane.showMessageDialog(null,"Deleted");
            usn.setText("");
            iia.setText("");
            iiia.setText("");
            iiiia.setText("");
            //subcode.setText("");
        }
        else
        {
          JOptionPane.showMessageDialog(null,"Not Deleted");
        }

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String subcode2;
        subcode2=subcode.getText();
        
        
        if(subcode2.equals(subcode1))
        {
        try{
        if(new StudentConnection().add(usn.getText(),iia.getText(),iiia.getText(),iiiia.getText(),subcode2))
        {
            JOptionPane.showMessageDialog(null,"Successfully Inserted");
            usn.setText("");
            iia.setText("");
            iiia.setText("");
            iiiia.setText("");
            //subcode.setText("subcode1");
        }
        else
        {
          JOptionPane.showMessageDialog(null,"Not saved");
          
        }
            }
         catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Data is already inserted for this usn and subcode in the table");

        }
       }
        else
        {
            JOptionPane.showMessageDialog(null,"You don't have permission to add for this subject code");
            usn.setText("");
            iia.setText("");
            iiia.setText("");
            iiiia.setText("");
            subcode.setText("subcode1");
        }
       
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel stable =(DefaultTableModel)iatable.getModel();
           try
           {
               Class.forName("com.mysql.jdbc.Driver");
               Connection conn =(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/studentdatabase", "root","root");
               Statement st=(Statement) conn.createStatement();
               for (int i = 0; i < iatable.getRowCount(); i++){
               for(int j = 0; j < iatable.getColumnCount(); j++) {
               iatable.setValueAt("", i, j);}
            }
             //DefaultTableModel dtm = (DefaultTableModel) iatable.getModel();
               stable.setRowCount(0);
               String query= "select * from editia where subcode='"+subcode1+"' order by USN;";// where USN=un;";
               ResultSet rs=st.executeQuery(query);
               while(rs.next())
                  {
                      String d1=rs.getString("USN");
                      String d2=rs.getString("IIA");
                      String d3=rs.getString("IIIA");
                      String d4=rs.getString("IIIIA");
                      String d5=rs.getString("subcode");
                      stable.addRow(new Object[]{d1,d2,d3,d4,d5});
                 }
          rs.close();
          st.close();
          conn.close();
        }
           catch(Exception e)
  {
          System.out.println("Error=" + "e.getMessage()");
           }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void iatableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iatableMouseClicked
        // TODO add your handling code here:
        String USN=iatable.getValueAt(iatable.getSelectedRow(), 0).toString();
        String IIA=iatable.getValueAt(iatable.getSelectedRow(), 1).toString();
        String IIIA=iatable.getValueAt(iatable.getSelectedRow(), 2).toString();
        String IIIIA=iatable.getValueAt(iatable.getSelectedRow(), 3).toString();
         String Subcode=iatable.getValueAt(iatable.getSelectedRow(), 4).toString();
        usn.setText(USN);
        iia.setText(IIA);
        iiia.setText(IIIA);
        iiiia.setText(IIIIA);
        subcode.setText(Subcode);
    }//GEN-LAST:event_iatableMouseClicked

    /**
    * @param args the command line arguments
    */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditIA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable iatable;
    private javax.swing.JTextField iia;
    private javax.swing.JTextField iiia;
    private javax.swing.JTextField iiiia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField subcode;
    private javax.swing.JTextField usn;
    // End of variables declaration//GEN-END:variables

}
