/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditAttendance.java
 *
 * Created on Sep 11, 2014, 4:10:29 PM
 */

/**
 *
 * @author Hare Ram
 */
//import amc.*;
import amc.*;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import amc.StudentConnection;

public class EditAttendance extends javax.swing.JFrame {

    /** Creates new form EditAttendance */
     String subcode1;
    public EditAttendance() {
        initComponents();
    }
     public EditAttendance(String subcod) {
          subcode1=subcod;
         initComponents();
         sub.setText(subcode1);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AttenTable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        ausn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        aiia = new javax.swing.JTextField();
        aiiia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        aiiiia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        sub = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("AMC ENGINEERING COLLEGE,BENGALURU");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amc.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Enter the Attendance");

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        AttenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USN", "1 IA", "2 IA", "3 IA", "Subcode"
            }
        ));
        AttenTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttenTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AttenTable);

        jButton5.setText("RETRIVE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("UPDATE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("DELETE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel4.setText("USN");

        jLabel5.setText("IIA");

        jLabel6.setText("IIIA");

        jLabel7.setText("IIIIA");

        jButton8.setText("EXIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel8.setText("Subcode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(ausn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(aiia, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jButton2))
                            .addComponent(aiiia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(35, 35, 35)
                                .addComponent(aiiiia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jButton3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel8)
                                .addGap(33, 33, 33)
                                .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton8)))))
                .addContainerGap(496, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(580, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ausn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(aiia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aiiiia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(aiiia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton8))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new FacultyLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //Connection conn=null;
        String subcode2;
        subcode2=sub.getText();
        if(subcode1.equals(subcode2))
        {

       if(new StudentConnection().addatten(ausn.getText(),aiia.getText(),aiiia.getText(),aiiiia.getText(),sub.getText()))
        {
            JOptionPane.showMessageDialog(null,"Successfully Inserted");
            ausn.setText("");
            aiia.setText("");
            aiiia.setText("");
            aiiiia.setText("");
            //sub.setText("");
        }
        else
        {
          JOptionPane.showMessageDialog(null,"Not saved");
        }
        }
 else
        {
            JOptionPane.showMessageDialog(null,"You don't have permission to add for this subject code");
            ausn.setText("");
            aiia.setText("");
            aiiia.setText("");
            aiiiia.setText("");
            sub.setText(subcode1);
 }

        
    }//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
for (int i = 0; i < AttenTable.getRowCount(); i++){
      for(int j = 0; j < AttenTable.getColumnCount(); j++) {
          AttenTable.setValueAt("", i, j);}
            }
             DefaultTableModel dtm = (DefaultTableModel) AttenTable.getModel();
            dtm.setRowCount(0);
            ausn.setText("");
            aiia.setText("");
            aiiia.setText("");
            aiiiia.setText("");

}//GEN-LAST:event_jButton2ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    // TODO add your handling code here:
     DefaultTableModel stable =(DefaultTableModel)AttenTable.getModel();
     for (int i = 0; i < AttenTable.getRowCount(); i++){
      for(int j = 0; j < AttenTable.getColumnCount(); j++) {
          AttenTable.setValueAt("", i, j);}
            }
            stable.setRowCount(0);
           try
           {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn =(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/studentdatabase", "root","root");
                Statement st=(Statement) conn.createStatement();
                String query= "select * from editattendance where subcode='"+subcode1+"' order by USN;";
                ResultSet rs=st.executeQuery(query);
               while(rs.next())
                  {
                      String d1=rs.getString("USN");
                      String d2=rs.getString("IIA");
                      String d3=rs.getString("IIIA");
                      String d4=rs.getString("IIIIA");
                      String d5=rs.getString("subcode");
                      stable.addRow(new Object[]{d1,d2,d3,d4,d5});
                  }
          rs.close();
          st.close();
          conn.close();
        }
           catch(Exception e)
  {
          System.out.println("Error=" + "e.getMessage()");
           }

}//GEN-LAST:event_jButton5ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    // TODO add your handling code here:
        int index=AttenTable.getSelectedRow();
        String usn1=AttenTable.getValueAt(index, 0).toString();
        String usn2=ausn.getText();
        String subcode2=sub.getText();
         if(subcode2.equals(subcode1))
         {
        if(new StudentConnection().updateatten(usn1,usn2,aiia.getText(),aiiia.getText(),aiiiia.getText(),sub.getText()))
        {


              JOptionPane.showMessageDialog(null, "Successfully Updated");

            ausn.setText("");
            aiia.setText("");
            aiiia.setText("");
            aiiiia.setText("");
           // sub.setText("");

        }
        else
        {
          JOptionPane.showMessageDialog(null,"Not updated");
        }
    }
        else
         {
             JOptionPane.showMessageDialog(null, "You don't have authority to update this subject code");
             ausn.setText("");
            aiia.setText("");
            aiiia.setText("");
            aiiiia.setText("");
            sub.setText(subcode1);

 }



}//GEN-LAST:event_jButton6ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    // TODO add your handling code here:
    String[] options={"yes","No"};
        int answ=JOptionPane.showOptionDialog(null,"Sure to delete??","Delete conform",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[1]);
        if(answ==0)
        {
            int index=AttenTable.getSelectedRow();
           String usn1=AttenTable.getValueAt(index, 0).toString();
           String subcod=sub.getText();
            if(new StudentConnection().deleteatten(usn1,subcod))
        {
            JOptionPane.showMessageDialog(null,"Deleted");
            ausn.setText("");
            aiia.setText("");
            aiiia.setText("");
            aiiiia.setText("");
            //sub.setText("");
        }
        else
        {
          JOptionPane.showMessageDialog(null,"Not Deleted");
        }

        }
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    // TODO add your handling code here:
    System.exit(1);
}//GEN-LAST:event_jButton8ActionPerformed

private void AttenTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttenTableMouseClicked
    // TODO add your handling code here:
    String USN=AttenTable.getValueAt(AttenTable.getSelectedRow(), 0).toString();
        String IIA=AttenTable.getValueAt(AttenTable.getSelectedRow(), 1).toString();
        String IIIA=AttenTable.getValueAt(AttenTable.getSelectedRow(), 2).toString();
        String IIIIA=AttenTable.getValueAt(AttenTable.getSelectedRow(), 3).toString();
        ausn.setText(USN);
        aiia.setText(IIA);
        aiiia.setText(IIIA);
        aiiiia.setText(IIIIA);
}//GEN-LAST:event_AttenTableMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AttenTable;
    private javax.swing.JTextField aiia;
    private javax.swing.JTextField aiiia;
    private javax.swing.JTextField aiiiia;
    private javax.swing.JTextField ausn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sub;
    // End of variables declaration//GEN-END:variables

}
