
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StudentIA.java
 *
 * Created on Sep 13, 2014, 9:55:32 PM
 */

/**
 *
 * @author Hare Ram
 */
public class StudentIA extends javax.swing.JFrame {

    /** Creates new form StudentIA */
    String USN1;
    public StudentIA() {
        initComponents();
    }
    public StudentIA(String usn1) {
        USN1=usn1;
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        iadetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nam = new javax.swing.JLabel();
        NAM = new javax.swing.JLabel();
        namee = new javax.swing.JLabel();
        Print_Command = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        iadetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SUBJECTS", "I IA", "II IA", "III IA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(iadetails);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("AMC ENGINEERING COLLEGE,BENGALURU");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amc.jpg"))); // NOI18N

        name.setFont(new java.awt.Font("Times New Roman", 0, 11));
        name.setForeground(new java.awt.Color(255, 51, 51));
        name.setText("IA DETAILS");

        jButton3.setText("DATA FETCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Name:");

        namee.setForeground(new java.awt.Color(255, 0, 0));

        Print_Command.setText("Print");
        Print_Command.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print_CommandActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(47, 47, 47)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(jButton1)
                        .add(70, 70, 70)
                        .add(jButton3)
                        .add(30, 30, 30)
                        .add(Print_Command)
                        .add(36, 36, 36)
                        .add(jButton2))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(Name)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jLabel3)
                                        .add(18, 18, 18)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(namee, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(NAM, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(jLabel1)))
                            .add(layout.createSequentialGroup()
                                .add(77, 77, 77)
                                .add(Nam))))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 550, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .add(name)
                .add(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(name)
                            .add(Name)
                            .add(jLabel3)
                            .add(Nam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(NAM)
                            .add(namee, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 217, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 72, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton3)
                    .add(jButton1)
                    .add(jButton2)
                    .add(Print_Command))
                .add(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new StudentLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel stable =(DefaultTableModel)iadetails.getModel();
           try
           {
//               String USN1=usn.getText();
//               System.out.println("Hi");
               Class.forName("com.mysql.jdbc.Driver");
               Connection conn =(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/studentdatabase", "root","root");
               Statement st=(Statement) conn.createStatement();
               for (int i = 0; i < stable.getRowCount(); i++){
               for(int j = 0; j < stable.getColumnCount(); j++) {
               stable.setValueAt("", i, j);}}
               stable.setRowCount(0);
               String query1= "select Name,subname,IIA,IIIA,IIIIA from subject,editia,student where student.USN='"+USN1+"'AND editia.USN='"+USN1+"' AND subject.subcode=editia.subcode ;";
                System.out.println("Hello");
               ResultSet rs1=st.executeQuery(query1);
//               String d5=rs1.getString("Name");
//               Name.setText(d5);
              // String d5;
               while(rs1.next())
                  {
                    String d1=rs1.getString("subname");
                    String d2=rs1.getString("IIA");
                    String d3=rs1.getString("IIIA");
                    String d4=rs1.getString("IIIIA");
                    String d5=rs1.getString("Name");
                    stable.addRow(new Object[]{d1,d2,d3,d4});
                    namee.setText(d5);
                  }

          rs1.close();
          st.close();
          conn.close();
        }
        catch(Exception e)
        {
          System.out.println("Error=" + "e.getMessage()");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void Print_CommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print_CommandActionPerformed
        // TODO add your handling code here:
        MessageFormat header =new MessageFormat(namee.getText()+": "+"Internal Assesment Report");
         MessageFormat footer =new MessageFormat("page{0,number,integer}");
         try
         {
             iadetails.print(JTable.PrintMode.NORMAL,header,footer);
         }
         catch(java.awt.print.PrinterException e)
         {
             System.err.format("Can't print %s %n", e.getMessage());
         }
    }//GEN-LAST:event_Print_CommandActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentIA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NAM;
    private javax.swing.JLabel Nam;
    private javax.swing.JLabel Name;
    private javax.swing.JButton Print_Command;
    private javax.swing.JTable iadetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel namee;
    // End of variables declaration//GEN-END:variables

}
